/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Organisers = {
	_type: 'organisers';
	title?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type Reviews = {
	_type: 'reviews';
	title?: string;
	review?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<{
			href?: string;
			_type: 'link';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
};

export type Gallery = {
	_type: 'gallery';
	title?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type Hero = {
	_type: 'hero';
	title?: string;
	text?: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?:
					| 'normal'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'blockquote';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
				_key: string;
		  }
	>;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
};

export type PageBuilder = Array<
	| ({
			_key: string;
	  } & Hero)
	| ({
			_key: string;
	  } & Gallery)
	| ({
			_key: string;
	  } & Reviews)
	| ({
			_key: string;
	  } & Organisers)
>;

export type Event = {
	_id: string;
	_type: 'event';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	slug?: Slug;
	headline?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'artist';
	};
	eventType?: 'in-person' | 'virtual';
	format?: 'in-person' | 'virtual';
	venue?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'venue';
	};
	date?: string;
	doorsOpen?: number;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	details?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<{
			href?: string;
			_type: 'link';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
	tickets?: string;
	firstPublished?: string;
	createdAt?: string;
};

export type Venue = {
	_id: string;
	_type: 'venue';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	city?: string;
	country?: string;
};

export type Artist = {
	_id: string;
	_type: 'artist';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	description?: string;
	photo?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type Page = {
	_id: string;
	_type: 'page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	pageBuilder?: PageBuilder;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type AllSanitySchemaTypes =
	| Organisers
	| Reviews
	| Gallery
	| Hero
	| PageBuilder
	| Event
	| Venue
	| Artist
	| Page
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageHotspot
	| SanityImageCrop
	| SanityFileAsset
	| SanityImageAsset
	| SanityImageMetadata
	| Geopoint
	| Slug
	| SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../web/src/sanity/lib/queries.ts
// Variable: HOMEPAGE_EVENTS_QUERY
// Query: *[  _type == "event"  && defined(slug.current)  && date > now()]|order(date asc){_id, name, slug, date}
export type HOMEPAGE_EVENTS_QUERYResult = Array<{
	_id: string;
	name: string | null;
	slug: Slug | null;
	date: string | null;
}>;
// Variable: EVENT_QUERY
// Query: *[    _type == "event" &&    slug.current == $slug  ][0]{  ...,  "date": coalesce(date, now()),  "doorsOpen": coalesce(doorsOpen, 0),  headline->,  venue->}
export type EVENT_QUERYResult = {
	_id: string;
	_type: 'event';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	slug?: Slug;
	headline: {
		_id: string;
		_type: 'artist';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		name?: string;
		description?: string;
		photo?: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	} | null;
	eventType?: 'in-person' | 'virtual';
	format?: 'in-person' | 'virtual';
	venue: {
		_id: string;
		_type: 'venue';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		name?: string;
		city?: string;
		country?: string;
	} | null;
	date: string;
	doorsOpen: number | 0;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	details?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<{
			href?: string;
			_type: 'link';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
	tickets?: string;
	firstPublished?: string;
	createdAt?: string;
} | null;
// Variable: PAGE_BUILDER_TYPES_ARRAY
// Query: *[_type == 'page'].pageBuilder[]{  _type}
export type PAGE_BUILDER_TYPES_ARRAYResult = Array<
	| {
			_type: 'gallery';
	  }
	| {
			_type: 'hero';
	  }
	| {
			_type: 'organisers';
	  }
	| {
			_type: 'reviews';
	  }
	| null
>;
// Variable: PAGE_BUILDER_QUERY
// Query: *[_type == 'page' && slug.current == $slug][0]{  _id,  _type,  pageBuilder[]{    ...,    _type,    _type == 'hero' => {      title,      text,      "image": image    },    _type == 'gallery' => {      title,      "image": image    },    _type == 'organisers' => {      title,      "image": image    },    _type == 'review' => {      title,      review,    }  }}
export type PAGE_BUILDER_QUERYResult = {
	_id: string;
	_type: 'page';
	pageBuilder: Array<
		| {
				_key: string;
				_type: 'gallery';
				title: string | null;
				image: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				} | null;
		  }
		| {
				_key: string;
				_type: 'hero';
				title: string | null;
				text: Array<
					| {
							children?: Array<{
								marks?: Array<string>;
								text?: string;
								_type: 'span';
								_key: string;
							}>;
							style?:
								| 'blockquote'
								| 'h1'
								| 'h2'
								| 'h3'
								| 'h4'
								| 'h5'
								| 'h6'
								| 'normal';
							listItem?: 'bullet' | 'number';
							markDefs?: Array<{
								href?: string;
								_type: 'link';
								_key: string;
							}>;
							level?: number;
							_type: 'block';
							_key: string;
					  }
					| {
							asset?: {
								_ref: string;
								_type: 'reference';
								_weak?: boolean;
								[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
							};
							media?: unknown;
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: 'image';
							_key: string;
					  }
				> | null;
				image: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					_type: 'image';
				} | null;
		  }
		| {
				_key: string;
				_type: 'organisers';
				title: string | null;
				image: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				} | null;
		  }
		| {
				_key: string;
				_type: 'reviews';
				title?: string;
				review?: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: 'span';
						_key: string;
					}>;
					style?:
						| 'blockquote'
						| 'h1'
						| 'h2'
						| 'h3'
						| 'h4'
						| 'h5'
						| 'h6'
						| 'normal';
					listItem?: 'bullet' | 'number';
					markDefs?: Array<{
						href?: string;
						_type: 'link';
						_key: string;
					}>;
					level?: number;
					_type: 'block';
					_key: string;
				}>;
		  }
	> | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'*[\n  _type == "event"\n  && defined(slug.current)\n  && date > now()\n]|order(date asc){_id, name, slug, date}': HOMEPAGE_EVENTS_QUERYResult;
		'*[\n    _type == "event" &&\n    slug.current == $slug\n  ][0]{\n  ...,\n  "date": coalesce(date, now()),\n  "doorsOpen": coalesce(doorsOpen, 0),\n  headline->,\n  venue->\n}': EVENT_QUERYResult;
		"*[_type == 'page'].pageBuilder[]{\n  _type\n}": PAGE_BUILDER_TYPES_ARRAYResult;
		"*[_type == 'page' && slug.current == $slug][0]{\n  _id,\n  _type,\n  pageBuilder[]{\n    ...,\n    _type,\n    _type == 'hero' => {\n      title,\n      text,\n      \"image\": image\n    },\n    _type == 'gallery' => {\n      title,\n      \"image\": image\n    },\n    _type == 'organisers' => {\n      title,\n      \"image\": image\n    },\n    _type == 'review' => {\n      title,\n      review,\n    }\n  }\n}": PAGE_BUILDER_QUERYResult;
	}
}
